#!/usr/bin/env bash
set -o errexit

# Check if a repository URL is provided as an argument
if [ -z "$1" ]; then
  echo "Usage: $0 git@github.com:laravel/laravel.git"
  exit 1
fi

REPO_URL="$1"
DEST_DIR="$2" # Optional: specify a destination directory
VERSION="$3"

# Extract repository name from the URL to use as default destination directory
REPO_NAME=$(basename "$REPO_URL" .git)

if [ -z "$DEST_DIR" ]; then
  DEST_DIR="$REPO_NAME"
fi

echo "Cloning repository: $REPO_URL"
echo "Into directory: $DEST_DIR"

# Clone the repository
git clone --depth 1 "$REPO_URL" "$DEST_DIR" --branch "$VERSION"

if [ $? -eq 0 ]; then
  echo "Repository cloned successfully to $DEST_DIR"
else
  echo "Error: Failed to clone the repository."
fi

git checkout -b master

#curl -s https://raw.githubusercontent.com/supravatm/docker-laravel/main/lib/template | bash -s $DEST_DIR

curl -L https://github.com/supravatm/docker-laravel/archive/main.tar.gz | tar xz --strip-components=1

mv compose/* ./
rm -rf compose README.md lib

# Ensure these are created so Docker doesn't create them as root
mkdir -p ~/.composer ~/.ssh

#docker run --rm -v "$(pwd)":/app composer install

#docker-compose exec app php artisan key:generate
#docker-compose exec app php artisan optimize