#!/usr/bin/env bash
set -o errexit

# Check if a repository URL is provided as an argument
if [ -z "$1" ]; then
  echo "Usage: $0 git@github.com:laravel/laravel.git"
  exit 1
fi

REPO_URL="$1"
DEST_DIR="$2" # Optional: specify a destination directory
VERSION="$3"

# Extract repository name from the URL to use as default destination directory
REPO_NAME=$(basename "$REPO_URL" .git)

if [ -z "$DEST_DIR" ]; then
  DEST_DIR="$REPO_NAME"
fi

echo "Cloning repository: $REPO_URL"
echo "Into directory: $DEST_DIR"

# Clone the repository
git clone --branch "$VERSION" --depth 1 "$REPO_URL" "$DEST_DIR"

if [ $? -eq 0 ]; then
  echo "Repository cloned successfully to $DEST_DIR"
else
  echo "Error: Failed to clone the repository."
fi

#curl -s https://raw.githubusercontent.com/supravatm/docker-laravel/main/lib/template | bash -s $DEST_DIR

cd $DEST_DIR

git init -qqq
git remote add origin https://github.com/supravatm/docker-laravel
git fetch origin -qqq
git checkout origin/main -- compose

mv compose/* ./
mv compose/.gitignore ./
rm -rf compose .git
git init

# Ensure these are created so Docker doesn't create them as root
mkdir -p ~/.composer ~/.ssh